env:
  REGISTRY: ghcr.io

jobs:
  build:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # with:
        #   ref: ${{ github.event.inputs.CLUSTER_NAME }}

      - name: Generate Timestamp
        run: |
          echo "TIMESTAMP=$(date '+%s')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}

      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
            context: .
            file: Dockerfile
            platforms: linux/amd64
            push: true
            tags: '${{ env.REGISTRY }}/agoric/tools-app:${{ env.TIMESTAMP }}'
            build-args: |
                TAG=${{ env.TIMESTAMP }}

name: Create Tools Docker Image

on:
  # workflow_dispatch:
  #   inputs:
  #     BRANCH_NAME:
  #       default: main
  #       description: Branch to build the image from
  #       required: true
  push:
    branches: ['usman/tools-app']
